### PR TITLE
fix: resolve symbolic links through `IO.FS.realPath` on windows

### LINKED ISSUE #810: `IO.FS.realPath` does not resolve symlinks on Windows
(as created by `mklink` or cmake using Developer Mode)

### PR DESCRIPTION
**Pull request by Rob23oba**
This PR fixes `IO.FS.realPath` on windows to take symbolic links into account.

Closes #810

### CODE REVIEW

**Comment by Rob23oba** [comment]
changelog-library

**Comment by ghost** [comment]
Mathlib CI status ([docs](https://leanprover-community.github.io/contribute/tags_and_branches.html)):
- ❗ Batteries/Mathlib CI will not be attempted unless your PR branches off the `nightly-with-mathlib` branch. Try `git rebase 3b72c7d1930197c07f35ea770ea13ff2ae4ddceb --onto 921ce7682e46544b536b3ab2901233b06c8165cf`. You can force Mathlib CI using the `force-mathlib-ci` label. (2025-05-29 20:53:28)
- ❗ Batteries/Mathlib CI will not be attempted unless your PR branches off the `nightly-with-mathlib` branch. Try `git rebase 3b72c7d1930197c07f35ea770ea13ff2ae4ddceb --onto 72141b05fd9a3328c1e5d99211dc4da4495cbd42`. You can force Mathlib CI using the `force-mathlib-ci` label. (2025-05-30 09:45:58)
- ❗ Mathlib CI can not be attempted yet, as the `nightly-testing-2025-06-01` tag does not exist there yet. We will retry when you push more commits. If you rebase your branch onto `nightly-with-mathlib`, Mathlib CI should run now. You can force Mathlib CI using the `force-mathlib-ci` label. (2025-06-01 11:41:28)

**Comment by Rob23oba** [comment]
release-ci

File: src/runtime/io.cpp [hunk 1]
```diff
@@ -958,17 +958,35 @@ extern "C" LEAN_EXPORT obj_res lean_io_realpath(obj_arg fname, obj_arg) {
...
+        if (memcmp(res, "\\\\?\\", 4) == 0) {
+            if (memcmp(res + 4, "UNC\\", 4) == 0) {
+                // network path: convert "\\\\?\\UNC\\..." to "\\\\..."
+                res[6] = '\\';
+                res += 6;
+            } else {
+                // simple path: convert "\\\\?\\C:\\.." to "C:\\..."
+                res += 4;
+            }
+        }
```
Comment (Kha) [inline src/runtime/io.cpp:983]: Is this adopted from anywhere else, any other reference?

Comment (Rob23oba) [reply src/runtime/io.cpp:983]: Originally Cameron told me about [this stackoverflow post](https://stackoverflow.com/questions/31439011/getfinalpathnamebyhandle-result-without-prepended/52861283#52861283). It also seems like some implementations have something similar, e.g. [java's file code](https://github.com/openjdk/jdk/blob/c1b5f62a8c30038d3b1a14d184535ba0642d51c9/src/java.base/windows/classes/java/io/WinNTFileSystem.java#L68).

Comment (Rob23oba) [reply src/runtime/io.cpp:983]: Also, from the documentation here: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
> The "\\\\?\\" prefix can also be used with paths constructed according to the universal naming convention (UNC). To specify such a path using UNC, use the "\\\\?\\UNC\\" prefix.

File: tests/lean/run/realPath.lean [hunk 2]
```diff
@@ -0,0 +1,19 @@
+def realPathTest : IO Unit := do
```
Comment (Kha) [inline tests/lean/run/realPath.lean:10]: Test is missing a docstring, https://github.com/leanprover/lean4/blob/master/doc/dev/testing.md#writing-good-tests
