### PR TITLE
fix: lake: lock test timeout + README typos

### LINKED ISSUE #2403: `leanlaketest_lock` can time out
See https://github.com/leanprover/lean4/actions/runs/5815446364/job/15767018271

### PR DESCRIPTION
**Pull request by tydeu**
Fixes #2403 and @Kha's follow-up comment in #2401.

### CODE REVIEW

File: src/lake/test/lock/test.sh [hunk 1]
```diff
@@ -12,6 +12,7 @@ fi
 ./clean.sh
 
 # Test lock file creation on build
+touch test.log
 $LAKE build Loop 2>&1 > test.log &
 grep -q "Building" < <($TAIL --pid=$$ -f test.log)
```
Comment (Kha) [inline src/lake/test/lock/test.sh:17]: Will `tail` not immediately exit if it sees the file from `touch` before the `lake` line opened it for the second time?

Comment (Kha) [reply src/lake/test/lock/test.sh:17]: Ah, of course not with `-f`! Clever.
