### PR TITLE
fix: use with_reducible in deriving_LawfulEq_tactic_step

### LINKED ISSUE #10416: deriving LawfulBEq fails when fields are structs
This fails:
```

structure Power where
  x : String
  k : Nat
  deriving BEq, ReflBEq, LawfulBEq

inductive Mon where
  | unit
  | mult (p : Power)
  deriving BEq, ReflBEq, LawfulBEq
```

Somehow the default tactic turns `(p == p) = true →` into  `(p.x == p.x) = true → (p.k == p.k) = true → ` which is not helpful.

### Version

Today’s head

### PR DESCRIPTION
**Pull request by nomeata**
This PR changes the automation in `deriving_LawfulEq_tactic_step` to use `with_reducible` when asserting the shape of the goal using `change`, so that we do not accidentally unfold `x == x'` calls here. Fixes #10416.

### CODE REVIEW

File: stage0/src/stdlib_flags.h [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #include "util/options.h"
 
+// please update stage0
+
```
Comment (nomeata) [inline stage0/src/stdlib_flags.h]:
```suggestion
```
