### PR TITLE
fix: only consider salient bytes in sharecommon eq, hash

### LINKED ISSUE #5831: `ShareCommon.Object.hash` assigns mismatching hashes to equal objects
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`ShareCommon.Object.hash` can assign mismatching hashes to objects considered equal.

### Context

[Broader context that the issue occurred in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

```lean
import Lean

unsafe def badHash (s : String) : UInt64 := ShareCommon.Object.hash <| unsafeCast s

def test : IO Unit := do
  let s2 := "tes"
  let mut s := "test"
  s := s.extract ⟨0⟩ ⟨3⟩
  unless s = s2 do throw <| .userError "Not equal"
  unless unsafe (badHash s == badHash s2) do throw <| .userError "Differing hashes"

#eval test
```
**Expected behavior:** no errors
**Actual behavior:** hashes do not match

### Versions

4.12.0-nightly-2024-10-24

### Additional Information

I may have a patch for this tomorrow.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by tkoeppe**
This PR changes `lean_sharecommon_{eq,hash}` to only consider the salient bytes of an object, and not any bytes of any unspecified/uninitialized unused capacity.

Accessing uninitialized storage results in undefined behaviour.

This does not seem to have any semantics disadvantages: If objects compare equal after this change, their salient bytes are still equal. By contrast, if the actual identity of allocations needs to be distinguished, that can be done by just comparing pointers to the storage.

If we wanted to retain the current logic, we would need initialize the otherwise unused parts to some specific value to avoid the undefined behaviour.

Closes #5831

### CODE REVIEW

File: src/runtime/sharecommon.cpp [hunk 1]
```diff
@@ -13,8 +13,8 @@ namespace lean {
 extern "C" LEAN_EXPORT uint8 lean_sharecommon_eq(b_obj_arg o1, b_obj_arg o2) {
     lean_assert(!lean_is_scalar(o1));
     lean_assert(!lean_is_scalar(o2));
-    size_t sz1 = lean_object_byte_size(o1);
-    size_t sz2 = lean_object_byte_size(o2);
+    size_t sz1 = lean_object_data_size(o1);
+    size_t sz2 = lean_object_data_size(o2);
     if (sz1 != sz2) return false;
```
Comment (eric-wieser) [inline src/runtime/sharecommon.cpp:18]: It's possible that this should reject objects as unequal if they have the same 'value' but differing capacities.

Comment (tkoeppe) [reply src/runtime/sharecommon.cpp:18]: That _used_ to be the case on account of L18, but is now no longer so. As long as the "value" is the same, we now compare equal regardless of capacity.

Comment (eric-wieser) [reply src/runtime/sharecommon.cpp:18]: Right, I was pointing this out for other reviewers; perhaps we should be more conservative and _only_ fix the undefined behavior without changing the behavior for objects with differing numbers of unused bytes.

Comment (tkoeppe) [reply src/runtime/sharecommon.cpp:18]: So you'd consider the total _size_ (but not contents) as salient, too? We could do that. It'd be good to then also include that size in the hash.

I'm not sure if this is overall desirable, though. I.e. why would you expect equal objects to have the same capacity? Wouldn't the capacity be checked locally by any operation that grows the contents, and not something you'd assume upfront?

That is, yes, we could make this change, but I'd hope that nothing would depend on that.

File: src/include/lean/lean.h [hunk 2]
```diff
@@ -398,6 +398,13 @@ static inline unsigned lean_ptr_other(lean_object * o) {
    small objects is a multiple of LEAN_OBJECT_SIZE_DELTA */
 LEAN_EXPORT size_t lean_object_byte_size(lean_object * o);
 
+/* Returns the size of the salient part of an object's storage,
+   i.e. the parts that contribute to the value representation;
+   padding or unused capacity is excluded. Operations that read
+   from an object's storage must only access these parts, since
+   the non-salient parts may not be initialized. */
+LEAN_EXPORT size_t lean_object_data_size(lean_object * o);
```
Comment (Kha) [inline src/include/lean/lean.h:406]: Removing the `byte` part from the name somewhat suggests this is not measuring bytes. Can we find a better name here, perhaps `lean_object_data_byte_size`?

File: src/runtime/sharecommon.cpp (hunk 1 above)
Comment (Kha) [reply src/runtime/sharecommon.cpp:18]: > we now compare equal regardless of capacity (and also hash equal)

How so, is `m_capacity` not part of the `memcmp` (and hash) as it is located after the `lean_object` header? I think your implementation is fine as is; I *don't* think we can assume that all `ShareCommon` users do not care about preserving capacity, identifying two objects with differing capacity may break referential transparency.

**Review by Kha — COMMENTED** [review]
LGTM all in all modulo comments

File: src/include/lean/lean.h (hunk 2 above)
Comment (tkoeppe) [reply src/include/lean/lean.h:406]: We can absolutely revise the names! I thought it was nice for "data" and "byte" to have the same length, but clarity should come first. Do you think "data_byte_size" is good (esp. when contrasted with the existing "byte_size")?

It seems reasonable that the longer term is more qualified, i.e. only the "data bytes" are being considered.

Comment (Kha) [reply src/include/lean/lean.h:406]: Yes, I'm happy with `lean_object_data_byte_size`

Comment (tkoeppe) [reply src/include/lean/lean.h]: Done!
