### PR TITLE
fix: avoid SIGFPE on x86_64 for ISize division overflow

### LINKED ISSUE #12097: #eval (- 2 ^ 63 : ISize) / (-1) crashes
### Prerequisites

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

There is a missing underflow check for `#eval (- 2 ^ 63 : ISize) / (-1)`. We have it already for other integer types.

### Context

[Broader context that the issue occurred in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

1.
2.
3.

**Expected behavior:** [Clear and concise description of what you expect to happen]

**Actual behavior:** [Clear and concise description of what actually happens]

### Versions

[Output of `#version` or `#eval Lean.versionString`]
[OS version, if not using live.lean-lang.org.]

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by eric-wieser**
This PR fixes a SIGFPE crash on x86_64 when evaluating `(ISize.minValue / -1 : ISize)`, filling an omission from #11624.

Closes #12097.

### CODE REVIEW

**Comment by eric-wieser** [comment]
changelog-language

**Comment by ghost** [comment]
Mathlib CI status ([docs](https://leanprover-community.github.io/contribute/tags_and_branches.html)):
- ❗ Batteries/Mathlib CI will not be attempted unless your PR branches off the `nightly-with-mathlib` branch. Try `git rebase f84aa23d6d8f60be1263b874c82528f1df18724e --onto 2c48ae7dfbc40059ec04cd0a702b34a144091d40`. You can force Mathlib CI using the `force-mathlib-ci` label. (2026-01-22 19:40:55)

**Comment by hargoniX** [comment]
Well that sure is curious :upside_down_face: @eric-wieser Does this maybe require an update-stage0?

**Comment by eric-wieser** [comment]
Probably not too important, since no one is doing this division in stage0

**Comment by eric-wieser** [comment]
Given the small diff, a back port might make sense though.

**Comment by hargoniX** [comment]
Right but you have to mark the stage0 update for the PR to go through, could you touch `stage0/src/stdlib_flags.h` and just add a random comment there for that to happen?

File: src/include/lean/lean.h [hunk 1]
```diff
@@ -2661,18 +2661,23 @@ static inline size_t lean_isize_mul(size_t a1, size_t a2) {
     return (size_t)(lhs * rhs);
 }
 
+
```
Comment (eric-wieser) [inline src/include/lean/lean.h]:
```suggestion
```
